### ISSUE TITLE
Options trading

### ISSUE THREAD

**Issue by EHrozner** [NelsonDane/public-invest-api#12]
Is there support for options trading in this api? Thanks

**Comment by NelsonDane** [comment]
No. I don't trade options so I'd have no way to add it. If someone puts in a PR for it tho I'd be happy to look at it!

**Comment by vpatelm3** [comment]
Hello sir. Is it possible to add in options trading? Just simple BTO requests. Buy a call or put. Then sell that call or put. I would be willing to donate for your time ❤️😊

**Comment by NelsonDane** [comment]
Hello @vpatelm3, As I mentioned above, I don't currently trade options, so I'm unable to add this at the moment. Perhaps in the future I or someone else will be able to add it through a PR

**Comment by NelsonDane** [comment]
Please see: https://github.com/NelsonDane/public-invest-api/pull/19 with discussion here: https://github.com/NelsonDane/public-invest-api/issues/15
