### ISSUE TITLE
Utils file

### ISSUE THREAD

**Issue by Cfomodz** [NelsonDane/public-invest-api#7]
Are you intentionally trying to not have a utils.py or some other sort of collection of shortcut/pattern functions and instead leaving it up to each person to craft what they need?

I don't mind cleaning mine up and committing it for you to consider, I just didn't want to waste the time if it's intentional; like maybe if you didn't want it to be 'too easy' for someone to stumble into yolo'ing SPY puts.

**Comment by NelsonDane** [comment]
I'm not purposefully not including it, I just didn't have one when I first created the project. As the project grows I'm sure one would be needed (especially for checking responses), and I welcome any contribution you want to make!
